language: node_js
node_js:
  - 12

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  on:
    branch: main