language: node_js
node_js:
  - 12

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  on:
    branch: main