language: node_js
node_js:
  - 12

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  on:
    branch: main