language: node_js
node_js:
  - 12
cache: npm
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: sarpere/sarpere.github.io
  on:
    branch: master
  local-dir: ./build
git:
  depth: 1
script: npm run build